# Generated by Django 5.1.6 on 2025-10-30 21:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('News', '0002_alter_imagemodel_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='description',
        ),
    ]
