# Generated by Django 5.1.6 on 2025-12-24 22:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('News', '0003_remove_category_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ['-created_at'], 'verbose_name_plural': 'News'},
        ),
    ]
