# Generated by Django 5.1.6 on 2026-01-26 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('News', '0005_alter_news_is_published'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='is_published',
            field=models.BooleanField(default=False),
        ),
    ]
